{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ include "rag-chatbot.name" . }}
type: Opaque
data:
{{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
{{- end }}
